src/diff.c
And added test that would trigger the bug in Valgrind.
=> Fix use-after-free when patch outlives diff

pygit2/index.py
Remove method, from index, can delete entries, based on different stages. https://libgit2.github.com/libgit2/#HEAD/group/index/git_index_remove
=> Remove items from index, based on stage

src/diff.c
=> Document that Diff.patch can be None

docs/install.rst
=> bump libgit2 version number

docs/install.rst
=> fix addition occurence of libgit2 version number

pygit2/repository.py
=> wrong order of the args in docstring of write_archive

pygit2/repository.py
Reference: https://github.com/libgit2/pygit2/issues/618
Signed-off-by: Igor Gnatenko <ignatenko@redhat.com>
=> repository: SYMTYPE is constant in module tarfile, not in any class

pygit2/repository.py
Reference: https://github.com/libgit2/pygit2/issues/620
Signed-off-by: Igor Gnatenko <ignatenko@redhat.com>
=> repository: decode() linkname

appveyor.yml
on AppVeyor for Windows (#655) broken by 865c2f0.
=> appveyor.yml Attempt to fix test run

pygit2/errors.py, pygit2/remote.py, test/test_remote.py, test/test_repository.py
This commit will fix the remaining failing windows tests.
=> Fix windows tests

src/repository.c, src/utils.c
This fixes two compiler warnings on master.
=> Fix trivial compile warnings

pygit2/decl.h, pygit2/repository.py, src/repository.c
Reimplemented `update_submodules` using cffi.
And added callbacks parameter.
=> Reimplement update_submodules method in ffi.

.mailmap, README.rst
=> Add my name, for the fame

src/worktree.h
=> Fix redefinition of typedef for gcc-4.3

docs/objects.rst
=> Document Object.short_id property

src/diff.c, src/reference.c, src/tag.c, src/types.h
For a project I am working on I added additional raw string fields to access strings that would otherwise throw a UnicodeDecodeError.
=> Add additional raw string fields

src/reference.c, test/test_refs.py
Adds equality support for Reference objects. Resolves #860
=> Reference object equality support

travis/build-manylinux1-wheels.sh
Signed-off-by: David Black <dblack@atlassian.com>
=> Download zlib over https.

pygit2/repository.py, src/reference.c, src/repository.c, test/test_branch.py, test/test_branch_empty.py, test/test_diff_binary.py, test/test_refs.py, test/test_repository.py
As seen on [the complimentary `git.sr.ht` branch](https://git.sr.ht/~nabijaczleweli/git.sr.ht/commit/utfucky-wucky-v2).
Ref: #1028
=> A few bytes-oriented interfaces

.github/workflows/tests.yml, .github/workflows/wheels.yml, build.sh, misc/build-manylinux-wheels.sh
Need to also update trove classifiers, tox's env, etc.
=> Add support for Python3.10

docs/index_file.rst, src/pygit2.c, src/repository.c, src/stash.c, src/types.h, test/test_repository.py
=> Add Stash type, Repository.listall_stashes

pygit2/callbacks.py
=> Fix _sideband_progress_cb never calls RemoteCallbacks.sideband_progress

build.sh, requirements.txt, setup.py
Closes: #1128
Signed-off-by: Konstantinos Smanis <konstantinos.smanis@gmail.com>
=> Define dependencies consistently using environment markers

pygit2/repository.py
See discussion in https://github.com/libgit2/pygit2/pull/1271#issuecomment-1907720802
=> Fix default value for file_flag in Repository.merge_commits

test/test_remote.py
=> Do not access freed memory in test_push_options()

.github/workflows/lint.yml, .github/workflows/wheels.yml
* https://github.com/libgit2/pygit2/issues/1364
=> ci: bump wheel and lint workflows to 3.13 - tested version

pygit2/_pygit2.pyi
See commits descriptions for the details.
@jdavid can you please take a look?
=> Typing fixes - remove deleted symbols from stub

docs/branches.rst
=> fix create branch example in docs
