libgit2/pygit2

pygit2/__init__.py
This fixes errors such as the following which occur when using any of the optional string parameters of init_repository():
```
Traceback (most recent call last):
[...]
pygit2.init_repository(repo_path, True, template_path=template_path)
File "/usr/lib/python3.4/site-packages/pygit2/__init__.py", line 89, in init_repository
options.template_path = to_str(template_path)
TypeError: initializer for ctype 'char *' must be a cdata pointer, not bytes
```
=> Fix data type of options in init_repository()

src/diff.c, src/types.h
My last patch introduced compiler warnings.  This patch fixes them and one other (`len` was unused).
=> Fix compiler warnings

docs/features.rst, docs/index.rst, pygit2/__init__.py, pygit2/decl.h
This lets us ask the library whether it supports threading, https and
ssh.
---
I wasn't sure whether to leave it with the int as-is or convert the result to a list of strings, so you can do
if 'ssh' in pygit2.features:
instead of
if pygit2.features & pygit2.GIT_FEATURE_SSH:
The former seems more in line with what a pure-python library would do, but we do expose the underlying flags in most places.
=> Add support for libgit2 feature detection

.gitattributes, pygit2/_utils.py
Two things here:
- Ensure git stores headers with LF line endings, so it's parseable by CFFI at runtime even on windows.
- If sys has attribute 'Frozen', we need to look in a different place for the decl.h file. This naively uses the current path of the executable, as I don't know where else to put it.
I'm not sure you'll want this in main, but it posed problems for me when using pygit2 in a frozen executable (Using cx_Freeze), where the python modules are loaded from a .zip file.
=> Make pygit work (for FAForever) in a frozen environment

pygit2/index.py, pygit2/remote.py, pygit2/utils.py
We need to keep hold of the strings which we create. We must also hold
on to the array of strings which we assing to our git_strarray.
We were not doing the latter, which meant that our strings may have been
freed too early, leaving us with with memory access errors (though often
not leading to a crash due to the custom allocator in python).
As we need to keep hold of two/three pieces of information, this looks
like a good place to introduce a context manager. This allows us to
keep these pointers alive without burdening the call sites with a return
of multiple objects they have no use for.
=> Safer handling of string arrays

docs/repository.rst, pygit2/decl.h, pygit2/repository.py, src/repository.c, test/test_repository.py
This lets us ask how many diverging commits each side of two histories have.
Unfortunately the libgit2 function is currently buggy, so we might want to avoid merging until we can create some tests which are actually accurate.
=> Add Repository.ahead_behind()

pygit2/repository.py
`repository.write_archive()` writes the contents of a file for symlinks, which causes tar to skip those bytes when extracting, and fail with an error code.  This patch fixes that issue.
=> Fix handling of symlinks in write_archive().

pygit2/repository.py
Currently, the `write_archive()` creates an archive that extracts the files in the "main root" directory.  This patch allows one to specify a path under which all the files will be extracted.
=> Add an option to specify root path when creating archives

docs/merge.rst, pygit2/decl.h, pygit2/repository.py, test/test_merge.py
This allows us more direct control over which trees to consider for merging.
=> Introduce Repository.merge_trees()

docs/install.rst
This should be considered as a primer to get you started on using pygit2 on OS X. Since I only have one Mac, I could not verify this on more OS Versions and / or settings.
=> Added installing on OS X

docs/recipes/git-show.rst
I couldn't get the diff as shown in the git-show recipe. Therefore
update it to what I think it should be. Maybe there is a better way.
Also add a section on how to assemble a git show-like message. It took
me quite some searching in the Python docs to find out how to do it,
especially the date and time part. So this might save people time. I
wanted to add something that gives me a git show --stat equivalent, but
couldn't figure it out.
=> Update git-show recipe

src/repository.c, src/repository.h, test/test_cherrypick.py
This adds limited support for the cherrypick() call only (not cherrypick_commit()). Addresses issue #436 
Learning Python, cffi and the internal workings of Git at the moment, would appreciate any feedback.
=> Add support for cherrypick()

docs/install.rst
Without `pkg-config` it is not possible to build `libgit2` with ssh support.
In `libgit2/CMakeLists.txt` the detection of `libssh2`library is done with `PKG_CHECK_MODULES`:
```
IF (USE_SSH)
PKG_CHECK_MODULES(LIBSSH2 libssh2)
ENDIF()
IF (LIBSSH2_FOUND)
ADD_DEFINITIONS(-DGIT_SSH)
INCLUDE_DIRECTORIES(${LIBSSH2_INCLUDE_DIRS})
LINK_DIRECTORIES(${LIBSSH2_LIBRARY_DIRS})
SET(LIBGIT2_PC_REQUIRES "${LIBGIT2_PC_REQUIRES} libssh2")
SET(SSH_LIBRARIES ${LIBSSH2_LIBRARIES})
ELSE()
MESSAGE(STATUS "LIBSSH2 not found. Set CMAKE_PREFIX_PATH if it is installed outside of the default search path.")
ENDIF()
```
If `pkg-config` package does not exist, it'll continue without adding `libssh2` support.
=> docs/install.rst: added pkg-config as a dependency for building libgit2.

pygit2/decl.h, pygit2/repository.py, test/test_repository.py
This allows us to generate a textual diff of conflicting files in
bare repositories by first performing a merge, retrieving the
IndexEntries of each conflict and then calling
Index.diff_index_entries(...).
=> Implement merging of index entries.

src/tree.c, test/test_tree.py
The value equality for TreeEntry needs to take the id into account. The
function we were using `git_tree_entry_cmp()` is only meant for
git-compatible sorting in a tree and thus does not take that into
account. Change `_richcompare()` to do so.
We then leave the git-copmatible sorting method as `TreeEntry.sortcmp()`
which can be used to ask python to use that as the comparison function
in `sorted()` and friends.
---
It might just be good enough to leave out `TreeEntry.sortcmp()` and just rely on richcompare, since the extra checking only comes in when they're otherwise equal.
=> Split TreeEntry's equality and sorting

pygit2/repository.py, test/test_repository.py
When merging index entries where the corresponding files contain Unicode
codepoints an error is thrown. Decode the C string using UTF-8 to fix the issue
and adjust the test case for merging files to contain umlauts to catch such
errors.
=> Fix error when merging files with unicode content.

pygit2/repository.py
I usually do `blob1.diff(blob2)` but I ran into this the other day and I figured I might as well just fix it. That said, it's not clear to me it's a good idea to have two different ways of doing (what seems to be) the same thing (i.e., `blob1.diff(blob2)` and `repo.diff(blob1, blob2)`) but I leave that up to you. (The other alternative is to have `repo.diff` be only for showing changes between WT, index, and head)
=> make diff of blob to blob in `repository.diff` work

pygit2/_utils.py
This makes pygit2 work with pyinstaller's onefile mode, and it should be a no-op if you are using something other than pyinstaller
=> make pygit2 work with pyinstaller

docs/recipes.rst, docs/recipes/git-cherry-pick.rst
Add the way that worked for me. Not sure if it is idiomatic. When doing
the convenience-mode cherry-pick, the repo remains in cherry-picking
mode afterwards. I've already added an issue for this.
Sorry for not following up on this one for a long time. This is the complete
thing now and I'll try not to mess up the pull request again.
=> Add git-cherry-pick recipes

src/repository.c
Change the argument "reference" to "reference_name", because "reference"
might lead to the assumption that one has to pass a pygit2.Reference.
=> Clarify docstring for Repository.create_commit

docs/diff.rst
I'm not the guy who looks at examples in the first place and I guess
there are other people like me. When I wanted find out how to get
information out of a Diff, I looked at the documented methods and didn't
find anything. Only later @cmn showed me the [p for p in diff] example
in the documentation. Add a short piece of information that gives a hint
to those who prefer the dry API docs.
=> Add hint to Diff.__iter__()

pygit2/decl.h, pygit2/remote.py, test/test_remote.py
This makes it a lot more convenient to create a remote and override the
fetch refspec it gets created with.
=> Allow creating a remote with a particular fetch refspec

docs/recipes.rst, docs/recipes/git-clone-mirror.rst
It's not necessarily obvious how to perform a mirror, so add a recipe
which tells what git does as well as provide example code of how to
perform the same steps in pygit2.
This should let us close #367 in good conscience.
=> Add a recipe for git clone --mirror

docs/diff.rst, src/diff.c, src/pygit2.c, src/types.h, test/test_diff.py
This wraps git_diff_stats and can be retrieved through a Diff. It
includes a formatting method.
I wasn't quite sure what to call the formatting function. It's called `_to_buf()` in C but the type is irrelevant in python, and something like `to_string()` didn't seem to fit as it takes options.
=> Add DiffStats

pygit2/remote.py
In the online documentation to Pygit2 it was not visible that (some of)
the parameters to Remote.fetch() and Remote.push() were optional. Fix
this. (I'm not sure if the way I did it is the idiomatic way of marking
a parameter optional in Python docstrings.)
=> remote.py: Denote optional parameters as such

pygit2/repository.py
IndexEntry._to_c requires its caller to hold a reference to the path it
returns until it no longer needs the C structure.
Repository.merge_file_from_index was not doing so, causing the merge
text to contain garbage from freed memory in some cases.
=> Keep path references in merge_file_from_index

docs/merge.rst, docs/recipes/git-cherry-pick.rst
In b3025e3fe I had written that when following my recipe, the repository
remains in cherry-picking mode afterwards. In issue #516 I was told that
Repository.state_cleanup() is needed to correct that. Therefore add it
to the recipe.
Also add a note near the documentation for cherry-pick, so that nobody
will overlook this again. Apparently there are other times when you need
to do Repository.state_cleanup() as well, but it's not documented, I
don't know when and I don't want to take the time and find out. So leave
it at that for now.
=> Cherry-pick recipe: clean up after picking

src/tree.c
When iterating over a tree, its entries show up as objects with an
address, which makes it hard to distinguish.
Add a method to handle repr and make it easier to play around with them
in the console.
=> Add repr output for TreeEntry

src/repository.c, test/test_repository.py
Not finding a merge base between two commits isn't an exceptional case,
it's just a different result.
=> Don't throw if there is no merge base

pygit2/remote.py
Looks like this was missed in the prep for v0.23.0
Without push_opts, pushing to a remote that requires authentication fails with the error:
`GitError: authentication required but no callback set`
=> Fix: pass push_opts to git_remote_push

.travis.yml, pygit2/__init__.py, pygit2/ffi.py, pygit2/libgit2_build.py, setup.py
Instead this does what is recommend in the CFFI docs here: https://cffi.readthedocs.org/en/latest/cdef.html?highlight=verify#out-of-line-api
This also means building the cffi extension is neatly handled by cffi's setuptools integration itself, so we can delete the code in setup.py that used to do this.
This change means it's easier to install pygit2 with the binary extensions bundled. It will fallback to the previous behavior in case the bundled extension was not found.
=> Don't use the deprecated cffi.verify by default

.travis.yml, pygit2/ffi.py, setup.py
I use pygit2 on Debian Jessie, which only has cffi 0.8.x.
I restored cffi 0.x support by following the instructions on https://cffi.readthedocs.org/en/latest/cdef.html?highlight=verify#upgrading-from-cffi-0-9-to-cffi-1-0.
I also tentatively restored PyPy tests on Travis.
=> Bring back cffi 0.x support

docs/objects.rst, src/tree.c, test/test_tree.py
This allows complete iteration and rebuilding of a tree without hitting
the object store for every entry.
=> Add type attribute to TreeEntry

docs/remotes.rst, pygit2/__init__.py, pygit2/errors.py, pygit2/remote.py, test/test_credentials.py, test/test_remote.py, test/test_repository.py
Instead of setting the methods/fields in the remote itself, which is a vestige of the older method which libgit2 used, have the user pass in an object with their callbacks, which represents what's going on underneath much more accurately, as well as letting us re-use the callbacks implementation across `Remote` and `clone_repsitory()`.
The docs aren't updated yet, so it's still WIP, but this is what I'd like us to move to.
=> Move remote callbacks to an interface/object

src/tree.c, test/test_tree.py
This mirrors the _message attribute for Tag, which gives you the raw
bytes from the entry name. Useful to parse repos where some filenames
aren't encoded as utf-8, such as https://github.com/wuts/earthquake.
=> Add _name attribute to TreeEntry

src/tag.c
A tag message can be empty. In that case, git_tag_message returns
NULL. PyBytes_FromString doesn't check its argument for nullness, and
therefore accessing _message on a tag with an empty message segfaults
Python.
=> tag._message: avoid NULL pointer dereference

docs/install.rst
For interacting / authenticating against an HTTPS repository we need the OpenSSL development headers present when installing pygit2, yet the documentation fails to mention it, which led to #573.
=> List OpenSSL as a dependency in the docs

docs/objects.rst, src/repository.c, test/test_blob.py
This commit allows blobs to be constructed from implementatons of the 'RawIOBase' ABC.  This allows any conformant stream implementation to be added as a blob.
This is useful in the case where the contents of the blob would be too large to create from memory (as 'create_blob_fromstring' allows) and avoids having to write the data to disk (as 'create_blob_fromworkdir' allows).  The latter operation is especially useful when reading data from a network socket, since it avoids having to first commit all the data to disk.
A failing test case was added which is fixed by this commit.
=> Implements 'Repository.create_blob_fromiobase'.

src/repository.c
The file object is passed to us, so we never incremented
its refcount. We shouldn't decrement it on exit.
=> Fix create_blob_fromiobase with pypy

docs/repository.rst, pygit2/decl.h, pygit2/repository.py, src/pygit2.c, test/test_describe.py
This method wraps the [describe functions](https://libgit2.github.com/libgit2/#HEAD/group/describe) using CFFI. It's useful, e.g., for automatically generating version numbers when using a Git repository for development. Let me know if there are any improvements or changes you'd like me to make!
Thanks!
=> Add support for Repository.describe(...).

test/test_diff.py
In a recent commit to libgit2, binary diffs were changed to have a
trailing empty line. This broke a test in test_diff because it compares
it directly against the string. I've added the extra line to the
expected output and the test now passes correctly.
The relevant libgit2 commit can be found here: https://github.com/libgit2/libgit2/commit/e4b2b919bb35d94d6dbcb5f7a31805788f2e335b
=> Fix broken binary diff test

pygit2/repository.py
=> Keep the describe dirty suffix string alive

pygit2/repository.py, setup.py, test/test_repository.py
This perhaps isnt' the most elegant fix, but otherwise all callers need to be patched.
Closes #588
=> Fix repository crash if path passed is not a str

src/repository.c
This exposes the libgit2 function for checking whether a path is ignored.
=> add method to check if a path is ignored

.gitignore, setup.py, tox.ini
Allow easy testing of the different environments supported by pygit2
=> Allow testing with tox

.travis.sh, pygit2/decl.h, src/types.h, test/test_config.py
The new release will be coming soonish, so here's an update for when that happens. Nothing too significant has changed. There's some new stuff, but this just aims to get the current features working with the newer version.
=> Update to libgit2 v0.24

test/test_remote.py
This is not how you define your callbacks, so this test isn't testing
for anything useful.
=> Remove checks for obsolete methods

docs/references.rst, src/repository.c, src/repository.h, test/test_refs.py
This allows for efficient reading of many references and their targets,
without incurring the overhead of lookup_reference() (which stats for
a loose ref and then reads packed-refs) which can be expensive on NFS
with thousands of refs.
We've been using this patch for a while and I think it makes sense for upstream pygit2. Any feedback on the idea?
=> repository: add listall_reference_objects() method

setup.py
Whilst working on the "reproducible builds" effort [0], we noticed that pygit2 could not be built reproducibly. This patch is fixing it.
[0] https://wiki.debian.org/ReproducibleBuilds
=> Make build reproducible

appveyor.yml
Currently there is only support for CI on linux powered by travis. This pull request adds a appveyor.yml file to support CI on windows using appveyor. Also the pygit wheel is provided as a build artifact, making it easier for windows users to install a pygit2 version. Unfortunately the unit tests do not pass yes, which appears to be a general windows/pygit2 issue.
An example of a build can be found here: https://ci.appveyor.com/project/fourplusone/pygit2/build/job/74l4rw3vp2sqv60d
I would love to hear the repository owners feedback on this
=> CI on windows

pygit2/repository.py
According to the old documentation, it was not clear how to compare 
working directory/index to a git object.
=> Ammend the doc-string of Repository.diff()

pygit2/errors.py
Libgit2 partially forwards OS error message texts.
I.e. the following error message (from C.giterr_last()) is generated on my german windows 10, when a fetch() is done but the remote repo is unavailable: ``failed to send request: Das Zeitlimit f\xc3\xbcr den Vorgang wurde erreicht.\r\n.``
To avoid that a UnicodeDecodeError due to the contained 'ü' (encoded as '\xc3\xbc') is raised the error message must be interpreted as UTF-8.
The solution is not be necessary on linux/osx as they return always ascii (as far as I know).
Thus this solution will not change the behaviour on linux/osx but fix windows issues.
=> Failure on non-ascii chars in error messages 

appveyor.yml
A followup to #655.
PowerShell script in testing does not fail build, see https://ci.appveyor.com/project/jdavid/pygit2/branch/master/job/ra1y9vjcva0exm6m and explanation at http://help.appveyor.com/discussions/problems/4498-powershell-exception-in-test_script-does-not-fail-build
=> appveyor.yml Attempt to fix test failure reporting

appveyor.yml
Another usability fix for #655.
/xunit/ endpoint in AppVeyor is made for uploading xUnit.net reports
http://help.appveyor.com/discussions/problems/5264-xunit-results-are-not-being-parsed
=> appveyor.yml Fix nosetests report upload

pygit2/remote.py
As happened in support request https://github.com/libgit2/libgit2/issues/3963 it can be easily overseen,
that push returns True, when the remote has installed a hook that denies the commits.
=> Extend comment of Remote.push by note about push_update_reference.

src/commit.c
`Commit` objects in git always have a `tree_id` associated, that points to the corresponding `Tree` object.
When the `Tree` object is missing, the repo is corrupted.
In those cases:
* official git cli fatals with status code `128` and message:
`fatal: unable to read tree <hash>`
* libgit2 returns error `GIT_ENOTFOUND` when calling `git_commit_tree()`
* pygit2 when accessing the tree by id with `repo[commit.tree_id]` raises a `KeyError: <hash>`
But on the other hand, on the commit object, rather than throwing and exception, pygit2 is swallowing the error returned by libgit2 and setting the `<Commit object>.tree` property to `None`.
This patch changes the behavior to raise an error in those cases.
**Rationale:**
`None` is arguably the wrong choice to encode an error condition, specially in …
=> Make pygit2 throw if tree of a commit is not found

.travis.sh, appveyor.yml, docs/install.rst, pygit2/decl.h, src/repository.c, src/types.h
We're hoping to have a release candidate for 0.25 this week so there won't be any more API changes.
This PR is just for the changes necessary to keep working with the new version and adding support for the new features like specifying a proxy is out of scope.
=> Update for v0.25

pygit2/repository.py
Removed a chunk of code from `checkout` that did nothing, but had a bug.
When checking out from a branch-less state (like the state when a repository is first initialized) the code failed.
The failure was due to trying to get some properties of the current branch, which were never used in the code.
=> Remove unused code

pygit2/repository.py, src/pygit2.c, src/repository.c
We use a `Capsule` to pass the `git_repository` struct through python. 
This `Capsule` does not need a destructor since libgit will free the `git_repository` struct when it needs to.
this addresses some of the needs for https://github.com/libgit2/pygit2/issues/76
=> Add support for custom backends

pygit2/__init__.py
Closes #688.
This can be solved in several ways, but this seemed the simplest and consistent with the issue discussion.
=> Added explicit check for `path = None` in `init_repository`

src/pygit2.c
=> Better error messages for opening repos.

docs/recipes/git-cherry-pick.rst, docs/references.rst, pygit2/repository.py, src/pygit2.c, test/test_branch.py
Closes #681
I'm not sure that there isn't other code that needs to be changed around there.
=> Normalize error handling for Repository_lookup_branch

docs/references.rst, pygit2/repository.py, test/test_refs.py
Same concept as the Repository.branches one.
Docs & tests already in place.
=> Added Repository.references accessor.

src/oid.c
Instead of using type punning to convert the OID to a Python hash, use
_Py_HashBytes() to hash the OID again. This means we no longer make any
assumptions on the internal representation of OID values or Python
hashes (before this commit, we at least relied on the fact that OID
hases are longer than Python hashes). Moreover, the random seed stored
in PYTHONHASHSEED is now honored.
This also fixes a compiler warning seen with -Wstrict-aliasing.
Signed-off-by: Lukas Fleischer <lfleischer@lfos.de>
=> Randomize OID object hashes

README.rst, pygit2/decl.h, pygit2/index.py, pygit2/repository.py, test/test_repository.py
This change adds `Repository.revert_commit()` which wraps around `git_revert_commit` which will return an `Index` with the appropriate changes to revert the specified commit.
Fixes #710
=> revert: Add support for git_revert_commit via Repository.revert_commit()

.travis.sh, docs/install.rst, src/types.h, test/test_config.py
The API isn't changing as much recently so all we needed to adjust was the
proper capitalisation of the error string.
I've left the version of pygit2 in code alone, as that should probably happen in changes for release on its own.
=> Update for libgit2 v0.26

docs/recipes/git-clone-ssh.rst, pygit2/credentials.py, pygit2/decl.h, pygit2/remote.py, test/test_credentials.py
This patch implements support for the ```GIT_CREDTYPE_USERNAME``` credential. The ssh transport requests this when negotiating authentication methods with libssh2. It seems the only other way to clone over ssh is to include the username in the repository URL, which is undocumented and inconsistent with the behavior prior to the credential callback.
=> improve credentials handling for ssh cloning

docs/references.rst
According to http://www.pygit2.org/references.html get_object() is deprecated, and we should be using peel() instead. Update the example at the top of the page to follow this advice.
=> Update example to use peel() instead of get_object().

.mailmap, README.rst, src/repository.c
This patch implements a repository member for cleaning up resources of the underlying repository struct without deallocating it. This is normally handled when deallocating the repository Python object. But longer running processes can run out of open file handles before the garbage collector runs.
=> add repository member for cleaning up open file handles 

pygit2/repository.py
The documentation for `Repository.describe()` hinted at the `GIT_DESCRIBE_*` options constants. 
List the valid constants and describe their behavior to make it clearer for the user.
=> repository: document describe_strategy options

docs/merge.rst
Documentation for merging branches contained an incorrect call to create_commit, that was missing the message parameter
=> Added missing parameter to method call in create_commit example

src/blob.c, src/patch.c, test/test_blob.py
Fixes #739 
PR Does the following:
* Adds the `patch` property to Patch objects, which follows the blueprint of `Diff.patch` almost exactly.
* Changes the parameter type for `Blob.diff_to_buffer` to allow for `None` as a valid parameter, signalling deletion.
* Adds two tests
=> Add patch Property to Patch Objects

test/test_repository.py
When running tests, I got a nag message about assertEquals being deprecated. This fixes the issue.
=> test_repository: Replace deprecated assertEquals with assertEqual

src/patch.c, test/test_patch.py
Fixes #742 
Does the following:
* Adds a new static `Patch.create_from` function which creates patches between various git primitives depending on the types of arguments provided.
* Adds test to verify the functionality
=> Add static Patch.create_from method to create patches

.mailmap, README.rst
I'm not sure if the contributors list is automatically created/updated or if we need to manually do it. I saw some people manually doing it, so I thought that I would too...
I contributed: #741  and #744
=> Add myself to contributors list 

src/patch.c
Full disclosure: I don't really understand why Windows builds are [failing for 0.26.2](https://ci.appveyor.com/project/jdavid/pygit2/branch/master). Quick google-foo suggests that it might be because declarations are not first..
I don't have a Windows machine to test on, so I'm going to use Appveyor to do the testing and verification.
=> Fix patch.c windows build errors

test/test_remote.py
This PR fixes the windows tests broken by #743
=> Clear clone_repo in Prune Test

src/patch.c, test/test_patch.py
Fixes #748 
For some reason, when using `repo.create_blob(CONTENT)` in the test cases, tests failed (as reported in the issue) on some machines (Did not fail on my Mac OS machine, Did not fail on AppVeyor Windows machines, **Did fail** on my CentOS machine).
I have no idea why that is. Perhaps I was doing something wrong.. perhaps there is something wrong with `create_blob`. I will create a followup issue to track it.
In any case, this PR fixes the issue by using the already existing repo blobs for the test cases. Further, after learning more about pygit2, I switched `create_from` to take optional params.
I think that 0.26.3 should be released after this PR is merged since 0.26.2 tests are broken for some users..
=> Use existing blobs in test_patch; Make create_from args optional

src/patch.c, test/test_patch.py
Adds support for specifying context_lines and interhunk_lines when calling `Patch.create_from`.
I've also added two tests to test the context lines functionality.
The behavior in this PR mimics the behavior in `tree.c` for adding these flags into the options.
=> Patch.create_from: Add support for context_lines and interhunk_lines

test/test_patch.py
Fixes deprecated test asserts warning introduced in #756
=> test_patch: assertEquals -> assertEqual

src/blob.c, src/diff.c, src/patch.c, src/patch.h, src/types.h
Fixes #754 and also allows merging of #758 .
As described in #754, Patch objects do not have a reference to their underlying blobs. Thus, if the blob is freed before patch text is generated, the patch text becomes mangled. This is ultimately an issue in libgit2 and the issue is being tracked in https://github.com/libgit2/libgit2/issues/4442
In the meantime, the problem can be solved at the pygit2 level. This PR adds blob references to the pygit2 Patch objects and increments their reference counters when a patch with blobs is generated.
When the fix is ultimately merged into libgit2, this behavior should probably be removed from pygit2. Until then, this is a good fix!
=> Give patch reference to underlying blob(s)

test/test_blob.py, test/test_patch.py
As reported in #754 , there are some strange corruption-looking things happening with creating patches. In order to find strange behavior, I've crafted the tests attached to this PR. 
At the time of writing, I could only get one of the tests to reliably fail: **test_patch_multi_blob**
```
Traceback (most recent call last):
File "/home/engshare/third-party2/pygit2/0.26.2/src/build-gcc-5-glibc-2.23/pic/test/test_patch.py", line 231, in test_patch_multi_blob
self.assertEqual(patch_text, [patch.patch for patch in patches])
AssertionError: Lists differ: [u'diff --git a/file b/file\nd... != [u'diff --git a/file b/file\nd...
First differing element 0:
diff --git a/file b/file
deleted file mode 100644
index a520c24..0000000
--- a/file
+++ /dev/null
@@ -1,3 +0,0 @@
-hello world
-hola mundo …
```
=> Add more tests to test_patch and test_blob

pygit2/blame.py, pygit2/config.py, pygit2/refspec.py, pygit2/remote.py, pygit2/utils.py
While Python 3 defaults to utf-8 in `bytes.decode()`, Python 2's
equivalent (`str.decode()`) will use the default encoding as set by
site.py (which is almost always ascii).
From looking at the code, it seems that these decodes have just sort of
been fixed piecemeal (likely when someone realized that pygit2 was
failing to handle unicode properly), but any decodes which run on Python
2 that don't specify utf-8 as the encoding are a ticking time bomb. I
personally noticed this was a problem when I encountered a traceback in
the RemoteCallbacks while fetching a new branch which contained utf-8
characters. During the fetch, when `pygit2.remote.maybe_string()` was
invoked by `_update_tips_cb()` with a pointer to a bytestring containing
unicode, the decode fails because the default encoding is …
=> Explicitly use utf-8 when decoding bytestrings

pygit2/credentials.py, pygit2/decl.h, pygit2/remote.py, test/test_credentials.py
Now we can use keys which are stored in memory objects.
=> git_cred_ssh_key_memory_new() support was added.

src/repository.c, test/test_repository.py
libgit2 has the ability to parse unified diffs from buffers, so why shouldn't pygit2?
This diff adds `Repository.parse_diff` to allow creating `Diff` objects from unified diffs on a certain repository.
Unit tests included!
=> Add Repository.parse_diff to wrap git_diff_from_buffer

src/diff.c, src/repository.c, test/test_diff.py, test/test_repository.py
I think this PR is a little less straight forward than #772 
I think the user should be able to create a Diff object from a unified diff without needing a repository, as in [`git_diff_from_buffer`](https://libgit2.github.com/libgit2/#HEAD/group/diff/git_diff_from_buffer). The existing pygit2 API, however, requires that a Repository be provided when creating a Diff object.
This PR relaxes that requirement and allows `NULL` to be provided for the Repository when creating a Diff object. This allows Diffs to be created without repos.
If this is a good idea, let's merge this in! If not, let's have a discussion. I'm also open to the idea of having an optional kwarg `repository=` so that we can reuse this code in `Repository.parse_diff`
=> Add static Diff.parse_diff

docs/config.rst, pygit2/config.py, test/test_config.py
This PR supersedes #776.
`Config.__iter__` iterates over a list of `ConfigEntry` objects instead of a list of names, matching the behavior of [`git_config_iterator`](https://libgit2.github.com/libgit2/#HEAD/type/git_config_iterator).
* Added a new `staticmethod`, `decode_as_string`, to simplify all the `ffi.string(value).decode('utf-8')` calls.
* Added a new flag to `_from_c`, `from_iterator=False`, to track the origin of the entry.
* Changed `__del__` behavior to only [`git_config_entry_free`](https://libgit2.github.com/libgit2/#HEAD/group/config/git_config_entry_free) `ConfigEntry`s created from [`git_config_get_entry`](https://libgit2.github.com/libgit2/#HEAD/group/config/git_config_get_entry). Attempting to free entries while iterating results in a seg fault. (If anyone can explain …
=> Refactor Config.__iter__ to iterate over ConfigEntry objects

src/pygit2.c, src/repository.c, src/repository.h, src/types.h, src/worktree.c, src/worktree.h, test/test_repository.py
This adds a unit test to the work done in #719 and #691, so that we can get this feature merged. It's also been rebased again, against the head of the `master` branch.
=> Finish worktree support

.travis.sh, docs/install.rst, pygit2/config.py, pygit2/decl.h, src/types.h
New release is out, so this is the customary update. Just one API change this time around.
=> Update to libgit2 v0.27

pygit2/remote.py
I just found a small typo in the documentation :slightly_smiling_face:.
=> Fix typo in documentation

docs/recipes/git-log.rst
The libgit2 walker is close to git-log in simple cases, but it does not
work quite the same way. For example, I've found that it does not return
the same number of commits compared to running "git log ref1..ref2".
=> doc: link to libgit2 ticket for git_log

docs/repository.rst, pygit2/repository.py, src/repository.c, test/test_branch.py, test/test_repository.py
Fixes issue #815
Let me know if this should be added to the docs, and if so, which section.
=> Add support for git_graph_descendant_of

docs/submodule.rst, pygit2/decl.h, pygit2/submodule.py, test/test_submodule.py
git_submodule_head_id is required for extructing the Oid targeted by a submodule
=> Added binding for git_submodule_head_id

pygit2/decl.h, pygit2/remote.py, test/test_remote.py
Add support for pruning a remote.
This change should fix this issue: https://github.com/libgit2/pygit2/issues/524
We need it in saltstack/salt in order to remove the dependency to git command line utility. 
Added a simple test
Signed-off-by: Cristian Hotea <cristian.hotea@ni.com>
=> Add support for pruning a remote

appveyor.yml, tox.ini
This PR changes the appveyor testing from nose to tox & pytest
=> Using tox & pytest in appveyor

test/test_refs.py
Together with #833, this PR will hopefully turn the windows build green again
=> Fix test_create_reference on windows

src/object.c, test/test_object.py
Resolves issue #852 by implementing `__eq__`, `__ne__`, and `__hash__` for git `_pygit.Object` types. Uses contained `Oid` as a unique identifier and falls back to the `Oid` operations for the same.
The net result is that the following now happens without issue
```python
>>> import pygit2
>>> repo = pygit2.Repository('.')
>>> repo.head.get_object() == repo.head.get_object()
True
>>> repo.head.get_object() != repo.head.get_object()
False
```
Note that unlike `Oid` `__ge__`, `__gt__`, `__le__`, and `__lt__` are not supported. These comparisions don't really make sense for `Object`.
As a bonus `Object` and its subtypes can be used in with `set` and other hash depenent containers. For example,
```python
>>> import pygit2
>>> repo = pygit2.Repository('.')
>>> s = set()
>>> …
```
=> add hash and equality operations on git objects

pygit2/repository.py
This fixes a bunch of typos that I noticed in the documentation (will need to redeploy docs if it doesn't happen automatically).
=> Fix Repsitory -> Repository in examples

pygit2/repository.py, test/test_repository.py
`Repository.checkout()` accepts a `paths` argument. A list of strings can be
passed with files to be checked out from the given reference. Current HEAD
will not be updated.
=> Add support for paths argument to checkout.

setup.py
This helps tools like pyup determine whether or not the library is Python3 compatible.
=> Add classifiers to publicize which versions of Python are compatible

.gitignore, .travis.sh, .travis.yml, test/test_commit.py, test/test_tag.py, travis/build-all-manylinux1-wheels.sh, travis/build-manylinux1-wheels.sh
Closes #793
In its current state the changed added in this PR enable Travis CI _build and publish_ OS-specific wheel distributions which are compliant with a manylinux1 standard.
This PR has a few intentionally incomplete bits:
1) it requires a PyPI password to be filled in
2) it requires uncommenting deploy stage clause so that publishing would only happen for tagged commits
Considerations
--------------------
For simplicity, this PR reuses image by pyca/cryptography which inherits the official image by pypa/manylinux1 and adds a pre-compiled openssl 1.1.1 on top of it so we don't have to.
As a further build time performance improvement I see how we can improve things by publishing our own image to a public registry (Docker Hub or better quay.io) but it's out of scope of this PR.
Credits …
=> Build manylinux1 OS-specific binary wheels in Travis (CI) and publish them to PyPI (CD)

.travis.yml, travis/build-manylinux1-wheels.sh
@jdavid this eliminates shared library dependencies.
=> Build manylinux1 compliant wheel statically

.travis.sh, appveyor.yml, pygit2/decl.h, src/mailmap.c, src/mailmap.h, src/pygit2.c, src/types.h, src/worktree.h, test/test_mailmap.py
This adds pygit2 support for the mailmap APIs added in https://github.com/libgit2/libgit2/pull/4586. It cannot be merged yet as-is due to using unreleased libgit2 APIs.
In addition, implementing this patch caused me to find https://github.com/libgit2/libgit2/pull/4688. Tests will fail on this PR until that PR is merged. I also noticed #803 while working on these.
=> Add mailmap support to pygit2

src/repository.c, src/repository.h, test/test_repository.py
Fixed #841 
This is a minimal version that does not accept options nor location. We can iterate on this.
Also, not sure if I should just accept the argument and cast it to `Diff*`, instead of properly check for its type. If yes, what is the idiom to do that? `PyArg_ParseTuple` only seems to accept positional arguments.
**DO NOT MERGE THIS**: this PR changes travis and appveyor to point to `master` of `libgit2`, since it is required for this feature to be tested. This should be changed to point to the release branch of a version of libgit2 that has the `git_apply` implemented in [this PR](
https://github.com/libgit2/libgit2/pull/4705)
=> Added Repository.apply

pygit2/settings.py, src/options.c, src/pygit2.c
Usage:
```python
import pygit2
pygit2.settings.ssl_cert_file = '/path/to/file'
pygit2.settings.ssl_cert_dir = '/path/to/folder'
del pygit2.settings.ssl_cert_file
pygit2.settings.set_ssl_cert_locations('/path/to/new/file', '/path/to/new/folder')
```
Co-Authored-By: Sriram Raghu <imbuedhope@gmail.com>
Closes #876
Superseeds and closes #879
=> Expose setting TLS file and dir lookup locations via settings module

pygit2/settings.py
Ignore TLS certificate lookup file and dir locations initialization
failure when the TLS backend library doesn't support it.
Ref #878
=> 🚑🐛 Fix TLS locations init when unsupported

docs/install.rst
Fix virtualenv build instructions for OSX, `LDFLAGS` syntax is different.
=> Improve OSX install documentation

src/repository.c, src/repository.h, test/test_merge.py
via new `Repository.merge_analysis_for_ref(our_ref, their_head)`
Upstream method was added in [libgit2 v0.28](https://github.com/libgit2/libgit2/releases/tag/v0.28.0)
Code-wise, follows the pattern + tests of the existing `Repository.merge_analysis()`
=> Support for git_merge_analysis_for_ref()

src/repository.c, test/test_repository.py
Adds suggestion from #814 by adding an optional positional parameter to `add_worktree`.
=> add_worktree: support optional target ref

src/repository.c, src/repository.h, test/test_merge.py
As suggested by @jdavid in https://github.com/libgit2/pygit2/pull/888#issuecomment-472542196
Base reference becomes an additional method parameter to `Repository.merge_analysis()`.
```python
my_repo.merge_analysis('abcde12345')                             # default ref is HEAD
my_repo.merge_analysis('abcde12345', 'refs/heads/other-branch')  # different ref
my_repo.merge_analysis_for_ref('refs/heads/other-branch', 'abcde12345')
```
=> merge: combine merge_analysis_for_ref() into merge_analysis()

pygit2/repository.py
This is fixing #616
I assume this is the correct way of solving this issue and it worked flawlessly in my (limited) tests.
=> Keep the original filemode on write_archive function

docs/install.rst
This was fixed by commit 01b69f31b613a99f2a5d47c96fde12b2d0c497d5
=> Install docs: remove pycparser warning

pygit2/config.py
Config.__init__() does not always set self._config, which can cause
trouble during __del__(). This avoids seemingly spurious and not
really helpful exceptions.
Fixes #916
=> Do not throw exception when Config.__init__() failed

pygit2/errors.py
`C.GIT_EEXISTS` was specified twice in the `Set` initializer, which was unnecessary and would lead to reader confusion.
=> Removed duplicate element in initializer

docs/objects.rst, pygit2/config.py, src/tree.c, src/tree.h, src/treebuilder.c, src/types.h, test/test_tree.py
Navigating tree objects is pretty crude via Pygit2 at the moment, requiring a lot of boilerplate lookups.
This change incorporates the same `/` operator approach as [Pathlib](https://docs.python.org/3/library/pathlib.html#operators) and [GitPython](https://gitpython.readthedocs.io/en/stable/tutorial.html?highlight=existing%20repository#the-tree-object):
* `my_tree / 'path'` resolves to a TreeEntry (same as `my_tree['path']` currently)
* If a TreeEntry is of type `tree`, then:
* `my_tree_entry / 'path'` resolves to a child TreeEntry
* `my_tree_entry['path']` and `my_tree_entry[0]` similarly
* `'path' in my_tree_entry` returns a boolean.
* this enables `my_tree / 'path' / 'path'` navigation
_Ideally_ I'd suggest that maybe Tree should probably be a subclass of TreeEntry so it kinda …
=> Improved support for navigating trees:

pygit2/decl/index.h, pygit2/index.py, test/test_index.py
Matches `Index.add_all()`, calls [`git_index_remove_all()`](https://libgit2.org/libgit2/#HEAD/group/index/git_index_remove_all) underneath:
```
myindex.remove_all(["*.txt", "foo.bar"])
```
=> Add `Index.remove_all()` method

pygit2/repository.py, src/repository.c, test/test_refs.py
Fixes #922 
1. `Repository.lookup_reference_dwim('master')` uses shorthand branch names, remote branches, tag names to find valid references
2. `Repository.resolve_refish('master')` additionally supports `HEAD`/`HEAD~1`/commit SHAs/etc, and returns a `(commit, reference)` pair.
=> Add support for ref-ish and do-what-i-mean reference lookups

AUTHORS.rst, CHANGELOG.rst, pygit2/decl/oid.h, pygit2/decl/remote.h, pygit2/remote.py, test/test_remote.py
Let me know if you need any changes here.
=> Add support for git_remote_ls()

pygit2/repository.py, src/object.c, src/odb.c, src/odb.h, src/pygit2.c, src/repository.c, src/repository.h, src/types.h, test/test_odb.py
Opening this now to start gathering feedback early, since I have little experience with Python's C API. The goal is to eventually support custom ODB backends written in Python. The steps to get here are roughly:
1. Add an Odb type and pull the odb out of Repository
2. Extend Odb with the rest of libgit2's odb API
3. Add a subclassable OdbBackend which maps to the C interface for custom backends
So far ~~only step 1 is complete.~~ step 1 and some of step 2 are completed.
=> Introduce Odb type

src/odb.c, src/odb_backend.c, src/odb_backend.h, src/pygit2.c, src/types.h, test/test_odb.py
The rough plan is to make the `OdbBackend` type a fairly straightforward mirror of the `odb_backend` in libgit2. I'll then be adding `LooseOdbBackend` and `PackOdbBackend`, and `MempackOdbBackend`, which will inherit from `OdbBackend` and set the underlying `odb_backend` pointer, which should Just Werk based on the approach I have set out so far.
The more interesting case is that of user-created `OdbBackend` implementations. I'm not really sure what to do for this yet. The first inch of this work is done in the form of the read call raising `NotImplementedException` if the C implementation is NULL, then through some kind of magic I assume I'll be able to set these to function pointers for some kind of proxy into Python code with some kind of magic base class. Or something. ¯\\\_(ツ)\_/¯
=> OdbBackend: initial groundwork

README.rst
Recent changes removed support for Python 2.7 and 3.4, as well as PyPy 2.7. Support was added for Python 3.8.
=> Correct supported Python versions.

src/branch.c, test/test_branch.py
A small change to expose the branch_name as bytes on the Branch class.
=> add raw_branch_name to pygit2.Branch

src/note.c, src/note.h, src/repository.c, src/types.h
Listing notes with below snippet of code could take a lot longer
than the equivalent git command: "git notes list".
```
import pygit2
repo = pygit2.Repository(".")
for note in repo.notes():
print(note.id, note.annotated_id)
```
To avoid this, lazily call git_note_read() only when more information
about the note is needed or when the note id is not provided.
=> note: lazily get all information about notes.

docs/references.rst, pygit2/repository.py, src/repository.c, test/test_refs.py
This exports the functionality of `git_refdb_compress`, which is the
equivalent of `git pack-refs --all`.  This is useful to improve
performance in some contexts on repositories with a large number of
refs.
=> Add References.compress

pygit2/decl/attr.h
When using libgit2 built from source, the build breaks due to a change
from git_attr_t to git_attr_value_t.  Update our headerfile
accordingly.
=> Fix build, change git_attr_t to git_attr_value_t

src/error.c, src/error.h, src/odb.c, src/odb_backend.c, src/pygit2.c, test/test_odb.py, test/test_odb_backend.py
The basic approach here is to have backends created from C (loose, pack) circumvent the OdbBackend_init function. However, backends created from Python will not. We then use this backend to pull out the functions implemented in Python and rig them up through shim functions to the libgit2 git_odb_backend.
TODO:
Separate patch?
=> [WIP] OdbBackend: Python subclassing

src/diff.c, src/diff.h, test/test_diff.py
Add binding for git patchid as mentioned in issue #877 
For the test to pass, it must be built against `fb439c975` in libgit2 where support for patchid has been improved.
=> diff: add support for patchid.

travis/build-manylinux1-wheels.sh
CI tries to print the Pygit2 features the wheel was built with, but it's actually not doing that. Fix it to follow the obvious intention.
=> ci: Fix for post-build feature detection in wheels

docs/install.rst, pygit2/__init__.py, pygit2/blame.py, pygit2/errors.py, pygit2/index.py, pygit2/remote.py, pygit2/repository.py, pygit2/settings.py, pygit2/submodule.py, setup.py
This resolve issues with binary top-level modules affecting [delocate](https://github.com/matthew-brett/delocate) on macOS (which helps with macOS wheel creation). Specifically, https://github.com/matthew-brett/delocate/issues/12#issuecomment-246536098
Change is that it moves (eg) `site-packages/_pygit2.cpython-37m-darwin.so` to `site-packages/pygit2/_pygit2.cpython-37m-darwin.so`, meaning the `_pygit2` internal api is available via `import pygit2._pygit2` cf `import _pygit2`
The impact this has building macOS wheels:
(fyi `delocate-listdeps` shows the libraries and what depends _on them_ indented)
Before:
```console
$ delocate-listdeps -d dist/pygit2-1.0.3-cp37-cp37m-macosx_10_15_x86_64.whl
/Users/rcoup/code/pygit2/venv/lib/libgit2.0.99.0.dylib:
_pygit2.cpython-37m-darwin.so …
```
=> Move _pygit2 to pygit2._pygit2

src/tree.c, test/test_tree.py
When doing nested iteration of a Tree, Python crashes with an Abort from a libgit2 assert in `git_tree_entry_byindex()`.
Code to reproduce:
```
for obj in some_tree:
if isinstance(obj, pygit2.Tree):
for obj2 in obj:
pass
```
Fix is to ensure `Tree`s are fully-loaded via `Object__load()` before creating a `TreeIter`, otherwise `self->owner->tree` in `TreeIter_iternext()` can resolve to `NULL`.
=> Fix abort with nested Tree iteration

pygit2/repository.py
I'm using this to get an index with conflicts into the workdir after using `merge_commits`.
API here: https://libgit2.org/libgit2/#HEAD/group/checkout/git_checkout_index
=> Allow checking out any given index

.github/workflows/macos.yml, README.rst, test/test_repository.py
Add macOS wheels into CI, using Github Actions macOS support.
* Built against Python 3.6, 3.7, 3.8 using the Python.org distributions, which means wheels are compatible with macOS 10.9+.
* Wheels run through [delocate](https://github.com/matthew-brett/delocate/) to embed libgit2
* Unit tests run/pass against the wheels
* Caches things fairly heavily, so total rebuild time is normally 2-3mins.
* Wheels are saved as artifacts, and are downloadable for 90 days.
Builds against `maint/v0.99` to match appveyor & travis, but it's configured as a matrix so can easily test against releases/branches/etc if appropriate. Not sure if we should be doing a "release" build `-DCMAKE_BUILD_TYPE=Release` (or `RelWithDebugInfo`), but it matches the other environments atm.
This was in the plan, but I think …
=> macOS Wheels

pygit2/index.py, pygit2/repository.py, pygit2/utils.py, src/pygit2.c, src/repository.c, src/utils.c, src/utils.h, test/test_attributes.py, test/test_blob.py, test/test_config.py, test/test_credentials.py, test/test_index.py, test/test_repository.py, test/test_submodule.py, test/utils.py
PEP-519 (Py3.6+ / PyPy 7.3+) adds a [file system path protocol[(https://www.python.org/dev/peps/pep-0519/) via `Object.__fspath__()`, and is supported by `pathlib`/`os`/`open()`/etc. This PR adds support for accepting `pathlib.Path` objects natively in Pygit2.
* Where we take paths in Python, check `hasattr(value, '__fspath__')` to provide Py3.5 compatibility, then call it to get a str/bytes representation.
* In C, use [`PyUnicode_FSConverter`](https://docs.python.org/3/c-api/unicode.html#c.PyUnicode_FSConverter) when parsing function arguments (it handles Pathlike objects), or [`PyOS_FSPath()`](https://docs.python.org/3/c-api/sys.html#c.PyOS_FSPath) when available (ie. not Py3.5).
* Implementation-wise, this approach is basically called for all string arguments, but since …
=> Accept Pathlike objects (eg. pathlib.Path) in Py3.6+

.github/workflows/macos.yml, .travis.sh, .travis.yml, appveyor.yml, docs/backends.rst, docs/repository.rst, pygit2/repository.py, src/odb_backend.c, src/pygit2.c, src/refdb.c, src/refdb.h, src/refdb_backend.c, src/refdb_backend.h, src/reference.c, src/repository.c, src/types.h, src/wildmatch.c, src/wildmatch.h, test/test_refdb_backend.py, test/test_repository.py
TODO:
Future work:
- Iterating over a refdb_backend from Python
- First-class reflog support
- Transactional refdb updates
=> Introduce Refdb type

src/object.c
While tab completing in the repl on the . of a blob object accessed not through the tree I caused a segfault.
I found out the repl calls inspect.getmemebers on the object which again tries to access raw_name.
I took the check from .name property and applied to to .raw_name
This is on python 3.8.2
Before fix
```python
>>> import os, pygit2, inspect
>>> r = pygit2.Repository("/home/user/repos/pygit2")
>>> b = r.get("855c845e538b")
>>> inspect.getmembers(b)
Segmentation fault (core dumped)
```
After fix
```python
>>> import os, pygit2, inspect
>>> r = pygit2.Repository("/home/user/repos/pygit2")
>>> b = r.get("855c845e538b")
>>> inspect.getmembers(b)
[('__class__', <class '_pygit2.Blob'>), 
('short_id', '855c845'), ('size', 444379), ('type', 3), ('type_str', 'blob')]
```
=> Obj reached not through tree caused Segmentation fault on raw_name access

pygit2/repository.py, test/test_merge.py
Up to now, Repository.merge_commits and Repository.merge_trees only
allowed the caller to choose the file_favor. This change also
allows them to set or unset any of the merge_flags or merge_file_flags,
while preserving the default behavior.
=> Allow setting merge options in Repository.merge

pygit2/index.py, test/test_index.py
IndexEntry is a simple datatype which can be usefully displayed or
compated to any other IndexEntry.
Not done for larger types Index or ConflictCollection since
its not clear if, for instance, two Indexes can be == if they have
different paths.
Added `ConflictIterator.__iter__` - this is required by the iterator
protocol. See
https://docs.python.org/3/library/stdtypes.html#iterator-types
=> Add repr, str, == and != support to IndexEntry.

pygit2/decl/submodule.h, pygit2/repository.py, test/test_submodule.py
Fixes #1010 
Implements the functionality required to add a submodule to the repository index
=> Add the ability to add a submodule to the repository index

test/test_diff.py
This is a faster and more idiomatic way of using `itertools.chain`. Instead of computing all the items in the iterable and storing them in memory, they are computed one-by-one and never stored as a huge list. This can save on both runtime and memory space.
=> Use chain.from_iterable in test_diff.py

src/blob.c, src/commit.c, src/object.c, src/object.h, src/pygit2.c, src/repository.c, src/revspec.c, src/revspec.h, src/tree.c, src/types.h, test/test_object.py, test/test_revparse.py
Expands revision parsing support:
1. adds `Repository.revparse_with_reference()` which maps to [`git_revparse_ext()`](https://libgit2.org/libgit2/#HEAD/group/revparse/git_revparse_ext) — takes the same arguments as `revparse_single()` but returns a 2-tuple `(Object, Reference)` where the revspec is a reference eg: `master`.
a. ❓ Not sure on naming? `find_revision()`?
b. ❓ Should we deprecate `Repository.revparse_single()` in favour of this rather than having two methods?
c. ❓ Or merge them via something like `revparse_single(revspec, with_reference=True)`
2. adds `Repository.revparse()` which maps to [`git_revparse()`](https://libgit2.org/libgit2/#HEAD/group/revparse/git_revparse) — does range requests (eg: `HEAD^1...new@{yesterday}`). Returns a `RevSpec` object which has `.from_object`, …
=> Expand revparse support

pygit2/utils.py
In `StrArray`, allow using tuples instead of lists for creating the array.
=> Allow using tuples as well as lists for StrArray

.github/workflows/macos.yml
Python builds support macOS 10.9, build libgit2 with the same macOS deployment target.
Fixes #1026
=> Fix wheel compatibility with older macOS

src/branch.c, src/diff.c, src/options.c, src/patch.c
The returned string may contain a '\0' character. Although not common, it
can happen e.g. in the diff output. Instead of truncating the output on the
null character, use the returned size from git_buf.
Fixes #1043
=> Use returned buffer size of git_buf

.github/workflows/macos.yml
`add-path` was deprecated and then removed recently:
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
=> Remove `add-path` command causing CI to fail

pygit2/config.py, pygit2/decl/config.h, test/test_config.py
https://libgit2.org/libgit2/#HEAD/group/config/git_config_delete_multivar
=> Add binding for git_config_delete_multivar

src/repository.c, test/test_repository.py
Add support for [`git_repository_is_shallow()`](https://libgit2.org/libgit2/#HEAD/group/repository/git_repository_is_shallow) to Pygit2 to indicate whether a repository is a [shallow clone](https://github.com/git/git/blob/master/Documentation/technical/shallow.txt) or not.
libgit2 currently [doesn't support shallow clones](https://github.com/libgit2/libgit2/issues/3058) beyond detecting there's a non-empty `.git/shallow` file but it's helpful nonetheless.
=> repository: add .is_shallow to detect shallow clones

pygit2/repository.py, src/repository.c, test/test_refs.py
Adds `message` keyword parameter to `Repository.create_reference...` functions.
Will close #1061.
=> refs: support message param when creating reference

pygit2/remote.py
=> Enable automatic proxy detection

pygit2/callbacks.py
=> Fix a tiny docs typo

docs/recipes/git-clone-mirror.rst
The documentation contains a recipe for how to emulate `git clone --mirror`. In
the example code, the init_remote callback constructs the mirror configuration
passing `name` to str.format. However, the callback receives the `name` (and
`url`) as bytes, so str.format would return something like this:
"remote.b'origin'.mirror"
This commit fixes the code example by decoding `name` when used with str.format.
The invocation of `repo.remotes.create` in the same example works fine as is,
because that function invokes `to_bytes` on its arguments, and `to_bytes` is a
noop when passed bytes.
=> Fix garbled mirror configuration in recipe for `git clone --mirror`

.github/workflows/wheels.yml, travis/build-all-manylinux-wheels.sh, travis/build-manylinux-wheels.sh
Added linux aarch64 wheel support.
Fixes #1077, @jdavid  Could you please review this PR?
=> Add linux aarch64 wheel support

appveyor.yml
Appveyor now has a support for the Python 3.10: https://github.com/appveyor/ci/issues/3741#issuecomment-958837889
=> ci/appveyor: build Python 3.10 wheel for Windows

.github/workflows/wheels.yml
macOS wheels are failing because the link is broken and the [official site](https://www.python.org/downloads/release/python-3100/) now points to https://www.python.org/ftp/python/3.10.0/python-3.10.0post2-macos11.pkg instead of https://www.python.org/ftp/python/3.10.0/python-3.10.0-macos11.pkg before.
Also, it now says that it has been updated for macOS Monterey.
CI failure: https://github.com/libgit2/pygit2/runs/4094160397
Also, see https://github.com/pypa/cibuildwheel/issues/902.
Testing on my fork https://github.com/skshetry/pygit2/runs/4094757646.
=> ci: fix broken link to macOS pkg for 3.10 Python builds

docs/recipes.rst, docs/recipes/git-clone-progress.rst, docs/recipes/git-commit.rst
Hi. I thought these might be helpful additions to the docs.
=> Add recipes for committing, and cloning with progress monitor.

src/odb_backend.c
The ODB backend class uses `PyArgs_ParseTuple` with format identifier `"n"` to parse `git_object_t` type IDs. However, `enum`s are not necessarily of type `Py_ssize_t`; in fact, the C standard does not constrain the underlying integer type. On big endian architectures such as s390x, this leads to unwanted cutoffs of the lower bits, yielding 0 instead of 3 as object type in `tests/test_odb_backend.py`.
This PR works around the issue by parsing the type into a well-known integer type first, and then casting to the `git_object_t` enum type, avoiding the undefined behavior.
=> Work around size mismatch between enum and Py_ssize_t

test/test_diff.py
The parse_diff function was moved out of Repository in the past, but some tests weren't updated to reflect this change.
The tests passed because they expected any exception to be raised, but they weren't actually calling the correct function (Diff.parse_diff).
=> Fix parse_diff tests not calling correct function

pygit2/repository.py
Specifying the type of `repository` in the constructors of `Branches` and `References` helps IDEs resolve the type of expressions such as:
repo.references["refs/remotes/origin/master"] ---> Reference
repo.branches.local["master"] ---> Branch
=> Improved type hinting in Branches, References

CHANGELOG.rst, docs/objects.rst, src/signature.c, test/test_signature.py
For better logging and easier debugging, this patch adds `str()` and `repr()` support to `Signature` type.
=> Add `str()` and `repr()` support to `Signature` type

pygit2/remote.py
Encoded again just below in
```
err = C.git_remote_fetch(self._remote, arr, opts, to_bytes(message))
```
=> Remove redundant to_bytes in remote fetch

.github/workflows/tests.yml, .github/workflows/wheels.yml
[Python 3.11.0rc1 is now released](https://pythoninsider.blogspot.com/2022/08/python-3110rc1-is-now-available.html), which is guaranteed to be ABI compatible with the final release.
And [the cibuildwheel v2.9.0 release](https://github.com/pypa/cibuildwheel/releases/tag/v2.9.0) includes Python 3.11 and builds wheels by default.
I also added a CI job to test with Python 3.11 in Linux so that any issues are caught. After final
release, we can remove the Python 3.10 version with 3.11 and reduce matrix that we are testing now.
Here's the GHA log for building wheels on my fork: https://github.com/skshetry/pygit2/actions/runs/2851936137.
=> bump cibuildwheel to 2.9.0 to build Python 3.11 wheels, also test on CI

pygit2/_pygit2.pyi, src/signature.c, src/utils.h, test/test_commit.py, test/test_signature.py
`to_unicode()` expects a non-NULL `x` argument (due to `strlen(x)`);
however `self->encoding` _may_ be NULL, especially if built with
`build_signature()` (i.e. if called from the `commit.author` property).
As a result, any `repr()` on a `Signature` with a NULL `encoding` will
cause a segfault.
Other functions manually map NULL to "utf-8" (see
`Signature__encoding__get__()`), so we'll do the same thing here.
=> Fix Signature repr()

AUTHORS.rst, src/signature.c
Addressing #1161 
If the representation of a signature requires the use of `Py_None` we should not decrement the reference count of the special `Py_None` object.
I tried adding a unit test to verify this new behavior, unfortunately, all the unit test I could come up with were not triggering the bug.
This was tested against the reproduce example in the issue setting the env var PYTHONPATH.
=> Remove decrement of reference when using Py_None #1161

pygit2/callbacks.py
refname was passed to push_update_reference as bytes.
However, the docstring for push_update_reference says refname is a string.
Also, refname is already passed as a string to another callback (update_tips).
=> RemoteCallbacks.push_update_reference: pass refname as a string

pygit2/callbacks.py, pygit2/repository.py, test/test_repository.py
Fix regression introduced by 25b5e0f (checkout & stash callbacks) in which custom checkout options weren't passed to git_stash_apply and git_stash_pop.
This PR also adds a unit test to ensure custom checkout options are honored during a stash apply or pop.
=> Fix checkout options within stash options

src/signature.c
`encoding` is strdup'd in `build_signature` regardless of whether the Signature has an owner.
So, `Signature_dealloc` must always free `encoding`.
=> Fix Signature memory leak

pygit2/remote.py
This `names()` iterator provides a big benefit in performance in my use case, where I want to test whether or not a remote exists for a large number of potential remote names (hundreds)
The first code I used looked something like:
```python
try:
repo.remotes[remote_name]
except KeyError:
repo.remotes.create(remote_name, remote_url)
```
However, this performs a lookup for all remote names, which was prohibitively expensive. So I decided to try collecting all the names into a set beforehand:
```python
existing_remotes = set(remote.name for remote in repo.remotes)
for remote_name, remote_url in wanted_remotes:
if remote_name not in existing_remotes:
repo.remotes.create(remote_name, remote_url)
```
However, this still performs a lookup for each remote to create the `Remote` objects yielded by …
=> Add RemoteCollection.names() iterator

appveyor.yml
Appveyor now has support for Python 3.11.
See https://github.com/appveyor/ci/issues/3844 and https://www.appveyor.com/updates/2022/11/07.
Related: https://github.com/libgit2/pygit2/pull/1154.
=> ci/appveyor: build Python3.11 wheel for Windows

pygit2/index.py, test/test_merge.py
This PR makes it possible to use the `in` operator with a ConflictCollection, e.g.:
```python
does_it_conflict = "some_path" in repo.index.conflicts
```
=> Add ConflictCollection.__contains__

pygit2/repository.py
Accessing each item in the tree during this loop slows down the `write_archive` method significantly when dealing with repositories with a large nr of files.
On a repository of ~5000 files the archiving time went from `13s` to `0.5s`.  
From what I can tell when testing `tree[entry.path].filemode` and `entry.mode` are the same.
=> Improve write_archive performance

src/signature.c, src/utils.c, src/utils.h, test/test_signature.py
Please see issue #1205 for details about this bug.
The proposed fix avoids undefined behavior by never passing NULL to PyUnicode_FromFormat.
=> Fix segfault in Signature.__repr__ & __str__ when the signature's encoding is incorrect or unknown (#1205)

.github/workflows/tests.yml, .github/workflows/wheels.yml, requirements.txt
Thanks for the great library :heart:!
Python 3.12.0 b3 is out, and the first RC will be out in July. Building a wheel now will allow other projects that depend on pygit2 to test with Python 3.12 without manually building libgit2.
This PR updates the version used for CI tests to 3.12-dev and updates cibuildwheel to get beta 3.12 support.
=> Test with and build Python 3.12 wheels

pygit2/decl/remote.h, pygit2/remote.py, test/test_remote.py
Adds support for `git_remote_create_anonymous` for creating anonymous (in-memory) remotes when you have a URL but do not want to create a named remote and the associated config entries
=> remotes: support anonymous remotes

docs/references.rst
The `Reference.log_append` method was removed 9 years ago in f35f58ca455c869263c97b28f77435fe626526ae. This removes an outdated reference to it in the documentation.
I think what happened here is that when the documentation was updated in 70410349ff6baf0714b671a6811e67770e672c89 to remove `log_append`, the example didn't get removed and instead was accidentally left under `log`.
=> Remove outdated log_append example

pygit2/filter.py, src/filter.c, test/test_filter.py
Follow up for https://github.com/libgit2/pygit2/pull/1237
- Exposes `FilterSource.mode` which was documented but missing a getter
- Fixes potential NULL `FilterSource.repo` handling and `FilterSource.repo` refcounting
- Fixes `Filter.check(..., attr_values)` list being shifted off by one (with an extra null/none value at index 0)
=> filter: fix FilterSource bugs

pygit2/__init__.py, test/test_repository.py
This adds a `depth` option to `clone_repository()` for shallow clones, which has been supported since libgit2 1.7.0: https://github.com/libgit2/libgit2/commit/190a4c55df72b32adf4d60f77cbc47276b74f84b
Note: The test for the shallow clone is currently online only due to libgit2 only supporting shallow clones of remote repositories. The git cli allows you to shallow clone a local repository if you use a file URI, but it seems that libgit2 doesn't support that.
fixes #1243
=> add `depth` option to `clone_repository()`

pygit2/remote.py, test/test_remote.py
Adds `depth` option to `fetch()`.
=> remote: add `depth` option to `fetch()`

pygit2/repository.py
This makes it easier to use those functions in an editor that supports type hints.
=> Add type hints for submodule functions in Repository

pygit2/repository.py, pygit2/submodule.py, test/test_submodule.py
Following up on https://github.com/libgit2/pygit2/pull/1248#issuecomment-1818816288, this PR implements a `Submodules` class that groups submodule functions in a Repository, much like `Branches`, `References` and `RemoteCollection`.
For backward compatibility, I turned the old functions into simple pass-throughs to the new class. Should we write unit tests for the deprecated versions?
=> Group submodule functions under Repository.submodules

docs/filters.rst
=> docs: fix typo on `CRLFFilter` example

src/filter.c, test/test_filter.py
All the calls to `pygit2_filter_payload_free` need the GIL to call `Py_DECREF` on the `pygit2_filter_payload` objects, but the [`filter.cleanup`](https://github.com/libgit2/libgit2/blob/4e7006ab4f37530c5f665948b464f1b579756d08/include/git2/sys/filter.h#L220-L228) callback was missing `PyGILState_Ensure` and causing a crash.
https://github.com/libgit2/pygit2/blob/8da921b4c2a6f8e64ad91e6395c0f3720df90083/src/pygit2.c#L322
https://github.com/libgit2/pygit2/blob/8da921b4c2a6f8e64ad91e6395c0f3720df90083/src/filter.c#L541-L546
https://github.com/libgit2/pygit2/blob/8da921b4c2a6f8e64ad91e6395c0f3720df90083/src/filter.c#L222-L234
```console
$ git init && touch file && git add file && git commit file --message=example
Initialized empty Git repository in /.../.git/
[main (root-commit) ...] example …
```
=> filter: ensure GIL during pygit2_filter_cleanup

pygit2/__init__.py, pygit2/_pygit2.pyi, src/diff.c, src/pygit2.c, src/repository.c, src/utils.c, src/utils.h, test/test_diff.py
Following up on #1251: C functions in _pygit2 now return actual Python enums instead of ints.
For example, Repository.status() would previously return simple ints. Now it returns FileStatus which transparently demotes to ints for legacy code:
```pycon
>>> repo.status()
{'file1.txt': <FileStatus.CONFLICTED: 32768>,
'file2.txt': <FileStatus.INDEX_MODIFIED|WT_MODIFIED: 258>}
```
Implementation details: References to the enums are cached via `cache_modules` so that lookups are faster. The references are decref'd in `free_module` (new module destructor function)
Affected functions:
- Repository.status
- Repository.status_file
- Repository.merge_analysis
- DiffFile.flags
- DiffFile.mode
- DiffDelta.flags
- DiffDelta.status
=> Return Python enums from _pygit2

.github/workflows/wheels.yml, build.sh, pyproject.toml
Resolves: https://github.com/libgit2/pygit2/issues/1216
=> Add wheel support for musllinux

docs/recipes/git-cherry-pick.rst
Using the parent of the cherry-picked commit as ancestor is not correct sometimes. That looks to be an issue because `base` was not used at all in the example whereas it should be used as ancestor.
=> Fix git-cherry-pick.rst example.

docs/recipes/git-cherry-pick.rst
The `base_tree` that must be used for a cherry pick is the cherry-picked commit parent.
=> Re-Fix git-cherry-pick.rst

docs/merge.rst, pygit2/decl/merge.h, pygit2/enums.py, pygit2/repository.py, test/test_merge.py
Merge functions now use new enums: MergeFavor, MergeFlag, MergeFileFlag.
These functions used to take a dict of strings to boolean flags (e.g. `flags={'no_recursive': True}`). Backward compatibility with this system was kept, and there are unit tests for that too.
As far as I'm aware, this system was only used in the merge functions and not anywhere else in pygit2. So, this PR aims to make these functions more consistent with the rest of the library, now that we use enums elsewhere.
=> Make merge API consistent with new enums

pygit2/_pygit2.pyi, pygit2/enums.py, src/object.c, src/pygit2.c, src/reference.c, test/test_refs.py
I missed those two properties in #1263.
`ReferenceType` was also updated to keep the names in sync with libgit2's enum deprecation (OID became DIRECT, LISTALL became ALL).
=> Return Python enums from Object.filemode and Reference.type

test/test_remote.py
On Fedora 40, this test fails with:
```
__________________________________ test_fetch __________________________________
emptyrepo = pygit2.Repository('/tmp/pytest-of-mockbuild/pytest-0/test_fetch0/emp tyrepo/.git/')
def test_fetch(emptyrepo):
remote = emptyrepo.remotes[0]
stats = remote.fetch()
>       assert stats.received_bytes == REMOTE_REPO_BYTES
E       assert 2760 == 2758
E        +  where 2760 = <pygit2.remote.TransferProgress object at 0xf60a7db0>.received_bytes
test/test_remote.py:218: AssertionError
```
Probably due to zlib-ng/zlib differences.
=> Relax transfer bytes check in test_remote.test_fetch

setup.py
The change from https://github.com/libgit2/pygit2/commit/aab211a842b17c8b699b2753301abb3a9ba7f1ad has incorrectly made setuptools a dependency of pygit2. It is not a runtime dependency, it is only a build dependency - `pkg_resources` / `setuptools` are not used outside of the installer script i.e. `setup.py`.
This change removes the setuptools dependency from package metadata, and makes it possible to use pygit2 without needing setuptools installed at all.
=> Remove setuptools runtime dependency on Python 3.12+

test/test_remote.py
On EPEL8 builds for s390x this transfers ~3040 bytes:
```
__________________________________ test_fetch __________________________________
emptyrepo = pygit2.Repository('/tmp/pytest-of-mockbuild/pytest-0/test_fetch0/emptyrepo/.git/')
def test_fetch(emptyrepo):
remote = emptyrepo.remotes[0]
stats = remote.fetch()
assert stats.received_bytes > 2700
>       assert stats.received_bytes < 2800
E       assert 3041 < 2800
E        +  where 3041 = <pygit2.remotes.TransferProgress object at 0x3ffa8668dd0>.received_bytes
test/test_remote.py:218: AssertionError
```
Would be too easy if this were deterministic.
=> Relax transfer bytes check even more

pygit2/index.py, pygit2/remotes.py, pygit2/utils.py, test/test_remote.py
With libgit2/libgit2#6439 having been recently merged, this PR attempts adding support for push options to pygit2.
While the basic code change (d387941a309804ac7bc198be4d34e4086204258f) is fairly trivial, I had to jump through some other hoops to get it to work.  Here is a summary of how this PR reached its current form:
1. First, I need a libgit2 version that supports push options.  Let's build it!
2. Oh no, push options only work in libgit2's `master` branch, not in libgit 1.7.2, which is the latest version that pygit2 currently works with.
3. Okay, let's hack around the current requirement for libgit2 1.7.x in pygit2's `master` branch.  (These changes are not included in this PR.)
4. This should be easy now, just turn a list of strings into a `git_strarray` and voilà.
5. Oh no, …
=> Add support for push options

pygit2/_pygit2.pyi, src/diff.c, test/test_diff.py
The docstring and type hints incorrectly state that `DiffDelta.status` returns a value of type `FileStatus` instead of `DeltaStatus`.
=> Fix docstring/type annotation for DiffDelta.status

pygit2/repository.py, test/test_submodule.py
`Submodule.open()` fails if the submodule was created from a subclass of Repository.
For example:
```python
class CustomRepoClass(pygit2.Repository):
pass
r = CustomRepoClass("some-repo")
s = r.submodules["submodule-name"].open()
```
This PR fixes this issue.
=> Fix Submodule.open() if parent repo is instance of Repository subclass

src/pygit2.c
Some C functions call Py_XDECREF on a PyBytesObject (representing a string), and then they pass a pointer within that object to `Error_set_str`. This causes the error message to appear corrupted if garbage collection occurs at just the right time.
For example, [`init_file_backend`](https://github.com/libgit2/pygit2/blob/584bda3c425cace5a984dd5b6b4abb5cc2e4166c/src/pygit2.c#L196) does something like this:
```c
PyBytesObject *py_path = ...;
const char* path = PyBytes_AS_STRING(py_path);
err = git_repository_open_ext(&repository, path, flags, NULL);
Py_XDECREF(py_path);  // <--- too early!
if (err < 0) {
Error_set_str(err, path);  // <--- path may be gone due to XDECREF above
goto cleanup;
}
```
The issue is that [PyBytes_AsString](https://github.com/python/cpython/blob/main/Objects/bytesobje …
=> Don't decref PyBytesObject before formatting an error with it

pygit2/submodules.py, test/test_submodule.py
When a submodule isn't in HEAD, [git_submodule_head_id](https://libgit2.org/libgit2/#HEAD/group/submodule/git_submodule_head_id) returns NULL.
pygit2's Submodule.head_id didn't check for ffi.NULL and built an Oid from garbage data in this case.
=> Fix Submodule.head_id if submodule isn't in superproject HEAD tree

pygit2/py.typed, setup.py
This PR adds the `py.typed` marker file (see: https://peps.python.org/pep-0561/ for reference). Without this file, static type checkers such as MyPy do not consider the library as typed. Thus this PR will resolve errors such as this:
```text
error: Skipping analyzing "pygit2": module is installed, but missing library stubs or py.typed marker  [import-untyped]
```
=> add py.typed

pygit2/decl/repository.h, pygit2/decl/types.h, pygit2/repository.py, test/test_repository.py
This exposes libgit2's [`git_repository_hashfile()`](https://libgit2.org/libgit2/#HEAD/group/repository/git_repository_hashfile).
`pygit2.hashfile()` already exists, but this lets you hash files using the repository's filters.
=> Add Repository.hashfile()

src/repository.c
It should be `const git_commit **`, not `git_commit **`.
Breaks the build with GCC-14.
[Complete build log](https://github.com/user-attachments/files/17631695/_log.txt) showing packages used and steps taken which lead to FTBFS.
=> fix: use correct type of the ninth parameter of git_commit_create()

pygit2/callbacks.py, test/test_remote.py
Fixes: https://github.com/libgit2/pygit2/issues/1262
I also added a test to ensure the callback is called on `ls_remotes`.
=> feat: add certificate_check callback to ls_remotes

.github/workflows/tests.yml
- [openssl@1.1 is disabled on the homebrew side](https://github.com/Homebrew/homebrew-core/blob/master/Formula/o/openssl%401.1.rb#L28-L29), bump to use openssl@3
- also update macos job to use py3.13
cc @jdavid
=> workflows/tests: update macos job

pyproject.toml
Associated with #1334. I noticed that while PyPy is officially supported no wheels for it are published to PyPI, setting up an env to build a wheel oneself is doable but unneeded as cibuildwheel handles this gracefully.
Link to successful Wheel build action: https://github.com/Spitfire1900/pygit2/actions/runs/12599295302/attempts/1
=> Build and release PyPy wheels to PyPI

.github/workflows/wheels.yml, pyproject.toml
In https://cibuildwheel.pypa.io/en/v2.22.0/options/#enable it's remarked that in cibuildwheel 2.x building PyPy wheels in implicitly enabled, but in cibuildwheel 3.x it must be explicitly enabled. The option to set this only is available beginning in cibuildwheel 2.22.0.
* Upgrade cibuildwheel to 2.22.0
* Explicitly enable PyPy builds in Wheel GitHub action
=> Explicitly build PyPy wheels - cibuildwheel 2.21.3 -> 2.22.0

pygit2/remotes.py, test/test_commit.py, test/test_merge.py, test/test_repository_bare.py
Fix incorrect condition in rename() method
Corrects a validation check in the remote renaming function where the first conditional was incorrectly checking new_name instead of name.
=> Fix condition check for current remote name in rename method

.github/workflows/codespell.yml, CHANGELOG.md, docs/development.rst, docs/install.rst, docs/merge.rst, docs/objects.rst, pygit2/__init__.py, pygit2/_build.py, pygit2/callbacks.py, pygit2/config.py, pygit2/decl/repository.h, pygit2/refspec.py, pygit2/remotes.py, pygit2/repository.py, pyproject.toml, src/odb_backend.c, src/pygit2.c, src/reference.c, src/repository.c, src/signature.c, test/test_repository_bare.py, test/test_tree.py
More about codespell: https://github.com/codespell-project/codespell .
I personally introduced it to dozens if not hundreds of projects already and so far only positive feedback.
CI workflow has 'permissions' set only to 'read' so also should be safe.
=> Add codespell support (config, workflow to detect/not fix) and make it fix few typos

.github/workflows/tests.yml
GitHub Actions has recently made it possible to use [Linux/aarch64 runners](https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/) in public repos. The tests now complete much faster than with `run-on-arch-action`.
=> CI: Run Linux/aarch64 tests on a real ARM runner without virtualization

pygit2/callbacks.py, pygit2/decl/callbacks.h, test/test_remote.py, test/test_repository.py
The existing callback `RemoteCallbacks.transfer_progress` is only called during fetches, not pushes.
This PR exposes libgit2's `push_transfer_progress` callback, allowing users to:
- Report progress during a push;
- Abort a push by raising an exception in the callback.
Note: I had to rewrite test_push_options to use a real RemoteCallbacks object instead of a mock object (the mock wasn't complete enough to work with my additions to git_push_options)
=> Add RemoteCallbacks.push_transfer_progress

pygit2/decl/commit.h, pygit2/repository.py, src/reference.c, test/test_merge.py
This PR allows passing more types to Repository.merge. Previously, you could only pass a commit ID as an Oid or an str.
In addition to these two, you can now also pass a real Commit, or a Reference.
Passing in a Reference will enrich the merge with additional information. For example, Repository.message will specify the name of the branch being merged, instead of just stating a commit ID:
```python
branch = repo.branches.local['other']
repo.merge(branch)
print(repo.message)  # "Merging branch 'other'"
```
If this PR is accepted, I believe passing an str should now be deprecated. The str is supposed to represent a commit ID, but users might intuit that the function also accepts ref names as an str, when in fact they should pass a real Reference object.
=> Allow passing a Reference to Repository.merge()

pygit2/remotes.py, test/test_remote.py
libgit2 supports creating pack files using multiple threads, which can significantly speed up a push operation.  Enable Remote.push() to take advantage of that capability by adding a relevant keyword argument whose value gets passed to git_remote_push().
The documentation for the new argument was ~~stolen from~~ inspired by [upstream docs](https://github.com/libgit2/libgit2/blob/b042e574064859c01cb902a3f4f418a3706eb78d/include/git2/remote.h#L863-L871).
=> Enable multi-threaded pack file creation

docs/repository.rst, pygit2/__init__.py, pygit2/callbacks.py, pygit2/remotes.py, test/test_repository.py
Fixes: #1328
```python
from pygit2 import clone_repository
url = "https://github.com/libgit2/TestGitRepository"
dest = "TestGitRepository"
main_branch = "master"
repo = clone_repository(url, dest, proxy=True)
```
=> Add proxy option to clone_repository

pygit2/__init__.py
It turns out this works in some situations but it should be avoided.
=> doc: warn against using init_repository() to open a repository.

.github/workflows/tests.yml
Will fix segfault occurring in this workflow
From runs-on-arch 
Note: New major release addressing sporadic segmentation faults
The release 3.0.0 addresses sporadic segmentation faults noticed with recent kernel releases, please update your action to this new major release (e.g. @v3) if you start noticing random or systematic CI failures.
Currently project not blocking on this failure due to  https://github.com/libgit2/pygit2/issues/812
But I think this is fixed and should be enabled again
=> Update tests.yml - bump run-on-arch to v3

pygit2/_pygit2.pyi
See example snippet - because of the issue with literal types `commit.type` type is detected as 'Unknown'. 
```python
import pygit2
repo = pygit2.Repository(r"L:\test")
for commit in repo.walk(repo.head.target, pygit2.GIT_SORT_TIME):
print(commit.type) # type detected by type checker is 'Unknown'.
print(commit.message)
break
```
After this fix the type becomes `Literal[1, 2, 4, 3]`.
It also resolves the issue with a couple overloads that use those types. E.g. running pyright on `_pygit2.pyi` before this fix:
```
pyright L:\Projects\Github\pygit2\pygit2\_pygit2.pyi
l:\Projects\Github\pygit2\pygit2\_pygit2.pyi
l:\Projects\Github\pygit2\pygit2\_pygit2.pyi:45:20 - error: Variable not allowed in type expression (reportInvalidTypeForm)
l:\Projects\Github\pygit2\pygit2\_pygit2.pyi:45:20 - error: …
```
=> stub - fix issues with literal types

pygit2/index.py, pygit2/repository.py, test/test_repository.py
In Repository.merge_file_from_index, pygit2 is only returning the resulting content out of the merge, however other values might be relevant like the filemode.
Add an optional flag to make it possible to get all the values coming out of git_merge_file_from_index instead of just the file content.
=> Repository: get an instance of MergeFileResult from git_merge_file_from_index

pygit2/remotes.py, test/test_remote.py
`Remote.ls_remotes` used to return a dict with str keys, which is inconsistent with how pygit2 generally returns structured results. This PR introduces `RemoteHead`, a class with fields.
Backwards compatibility with the old-style dict was kept via `RemoteHead.__getitem__` which emits a `DeprecationWarning`.
Also, when the `local` flag is off, `RemoteHead.loid` now forwards oid zero (`0000000`) as returned by libgit2 instead of making it `None`.
--- 
Tangent: I think `ls_remotes` is a bit of a confusing name. Perhaps something like `list_heads` or `advertised_heads` would be more intuitive, but this could be for another PR. What do you think?
=> Improve usability of `Remote.ls_remotes`'s result

mypy.ini, pygit2/blame.py, pygit2/callbacks.py, pygit2/ffi.py, pygit2/repository.py, setup.py, test/test_index.py, test/test_tag.py, test/test_tree.py
This intoduces a stricter mypy config.
The first step just fixes some unused type ignores.
All according to this doc:  https://mypy.readthedocs.io/en/stable/existing_code.html#getting-to-strict
Following the above mentioned doc just becauses i needed some plan of action.
@BenediktSeidl Please take a look.
Comments/suggestions welcome.
=> First round of mypy fixes

pygit2/_run.py, requirements-test.txt, setup.py
This hopefully helps with future typings.
=> Add types-cffi to test requirements

pygit2/remotes.py, test/test_remote.py
This PR implements changes discussed in https://github.com/libgit2/pygit2/pull/1397#issuecomment-3182758075
=> Deprecate Remote.ls_remotes in favor of Remote.list_heads
